packages:
  - "packages/*"
allowBuilds:
  better-sqlite3: true
  esbuild: true
  sharp: true
onlyBuiltDependencies:
  - better-sqlite3
  - esbuild
  - sharp
patchedDependencies:
  oceanic.js@1.14.0: patches/oceanic.js@1.14.0.patch
